# Generated by Django 4.2.2 on 2023-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_tilte', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('PT', 'Part Time'), ('FT', 'Full Time')], max_length=12)),
                ('job_description', models.TextField(max_length=1200)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('exp', models.IntegerField(default=0)),
                ('salary', models.FloatField(default=0.0)),
            ],
        ),
    ]
